### ISSUE TITLE
How to pass paramater in the rest api

### ISSUE THREAD

**Issue by dprabhua** [smartrics/RestFixture#121]
I am very new to Rest api and RestFixture, below is the curl statement , Can u please help how to use in this RestFixture, 

curl -H "X-DEMO-API-KEY-AUTH:true" -H "Content-Type:application/json" -u admin_jr:9257D59BC80D6545 https://xxxx.yyyyyy.com:443/v1/users -k

i tried something like this, but it is not working failing because of authentication,

|Table:smartrics.rest.fitnesse.fixture.RestFixture|https://xxxx.yyyyyy.com:443                         |
|setHeader                                        |X-DEMO-API-KEY-AUTH : true, admin_jr:9257D59BC80D6545  |
|GET                                              |/v1/users  |500 |Content-Type:application/json |no-body |

The response we are getting like this
{"status":500,"code":500,"err":"An error occurred while processing your request.","devMessage":"java.lang.String cannot be cast to com.osmosix.commons.user.OsmosixUserDetails","moreInfoUrl":"mailto:info@cliqr.com"}

**Comment by smartrics** [comment]
You can set multiple headers, one on each line:

|Table:smartrics.rest.fitnesse.fixture.RestFixture|https://xxxx.yyyyyy.com:443 |
|setHeaders |!- X-DEMO-API-KEY-AUTH : true
admin_jr:9257D59BC80D6545 -! |
|GET |/v1/users |500 |Content-Type:application/json |no-body |

on the last row you are saying that you expect the server to return a response code of 500, an header with Content-Type: application/json and a response with no body.

**Comment by dprabhua** [comment]
No luck this time getting the same error,
{"status":500,"code":500,"err":"An error occurred while processing your request.","devMessage":"java.lang.String cannot be cast to com.osmosix.commons.user.OsmosixUserDetails","moreInfoUrl":"mailto:info@cliqr.com"}

1. Is -u used by curl is same as header?
2. I expect the users list in the response in the json, not as empty body
3. The same error comes in browser since the authentication is failing.

Please help me to set authentication details.

**Comment by smartrics** [comment]
If you need to supply basic auth credentials then you should use he config
properties

http.basicauth.username
http.basicauth.password

Basic auth is the only auth method supported

No luck this time getting the same error,
{"status":500,"code":500,"err":"An error occurred while processing your
request.","devMessage":"java.lang.String cannot be cast to
com.osmosix.commons.user.OsmosixUserDetails","moreInfoUrl":"mailto:
info@cliqr.com"}

   1. Is -u used by curl is same as header?
   2. I expect the users list in the response in the json, not as empty body
   3. The same error comes in browser since the authentication is failing.

Please help me to set authentication details.

—
Reply to this email directly or view it on GitHub
<https://github.com/smartrics/RestFixture/issues/121#issuecomment-101368853>
.

**Comment by smartrics** [comment]
Please re-open this issue if the problem persists
