### ISSUE TITLE
Is it possible to compare response JSON fully not by element

### ISSUE THREAD

**Issue by abelyaevskiy** [smartrics/RestFixture#125]
Hello!

I found great possibility to check response JSON object via JavaScript. E.g. I have object {field1:value1, field2:value2}, so I can do following check 

    jsonbody.field1 == value1 && jsonbody.field2 == value2

Is it possible to simplify such check by providing full JSON I expected, e.g.

    jsonbody == ${JSONIExpected}
?

**Comment by smartrics** [comment]
Hello, i am not sure how exactly you wish to perform the check.
You could consult this: http://adripofjavascript.com/blog/drips/object-equality-in-javascript.html

I would advise against this approach though because it makes the test much more brittle; it also makes it less readable.

I'd prefer to compare as you did earlier the key fields of your objects.

**Comment by abelyaevskiy** [comment]
Thanks for the link! I think in same way with you. I will try to convince my teammates. Also. great thanks for the fixture!
