### ISSUE TITLE
Would the Rest Fixture support the HTTP Patch Method in future releases?

### ISSUE THREAD

**Issue by piyushsmantri** [smartrics/RestFixture#131]

**Comment by smartrics** [comment]
No - it doesn't... feel free to implement it and send a pull request though!

On 3 September 2015 at 00:19, piyushsmantri <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/131>.
>



-- 
Regards,

 Fabrizio

**Comment by Zordid** [comment]
Oh no! I need that, too! Why doesn't it support it? What's so complicated about just another verb??

**Comment by smartrics** [comment]
No reason... only that no one has needed it before. feel free to implement it and send a pull request though!

**Comment by Zordid** [comment]
Hmm. How? ;-)

Am 27. Juni 2017 15:49:37 MESZ schrieb Fabrizio Cannizzo <notifications@github.com>:

**Comment by gp12** [comment]
I'm having the same requirements to test PATCH method. 
But in order to implement PATCH, the dependency commons-httpclient needs to be upgraded to version higher than 4.2. (HttpPatch method is introduced in version 4.2). I'm going to update the restclient pom and implement the PATCH in restFixture. Smartrics, Please let me know if you have any suggestions on the approach. 

Thanks

**Comment by smartrics** [comment]
Hi - that's cool... there's a pattern you can follow similar to the other HTTP verbs.
I'd ask to write unit tests appropriately and also a sample page on the new feature in RestFixtureLiveDoc, IE a page where you demo the use of the verb which will also work as a regression pack.
I am happy to comment on your pull request if you send it or along the way if you feel to do so.

**Comment by smartrics** [comment]
please send PR  - I won't be able to do these changes
