### ISSUE TITLE
How to validate complex JSON Response?

### ISSUE THREAD

**Issue by kadimulam** [smartrics/RestFixture#176]
This is in continuation to #175. As #175 is closed, elaborating my question here. Could you please clarify?

For a complex JSON output, are you saying that the developer need to write the comparing logic on jsonbody object to compare the expected and actual output? I wanted to check with you if RestFixture automatically compares the expected and actual output (JSON) and then either passes/fails the test case. Is it possible?

If the developer need to write the comparing logic to verify the JSON reponse, it would be huge for comparing a huge JSON. Moreover, the tests in the Wiki are written by QA/business teams who do not have such technical ability. Am i missing anything? Please correct me if i am wrong.

**Comment by dnygaard** [comment]
A method I did was to extend the RestFixture class and add functionality, i.e. compare functionality from the Jackson JSON-library. I believe I set up functions that could compare JSON-trees strict and non-strict as well as "Does the REST-response JSON contain the following sub-JSON-tree?"

My non-technical QA-teammembers could then focus on how they expected the JSON responses to be like instead of hand-coding js.

**Comment by kadimulam** [comment]
Yes, i was looking for something like this. Let me do some analysis on this. If any questions, i will reach you.

Does your project "JsonRestFixture", implements this?

**Comment by smartrics** [comment]
Comparing JSON syntactically can be done very quickly by performing string comparison like:

    "{ 'value' : 1 }" === JSON.stringfy(jsonbody);

In my view this is too brittle though because the string comparison is susceptible to order of attributes in the object and values that are depending on the specific request (like random numbers, UUID, timestamps etc).

If your JSON doesn't include values that are request specific, you can do a deep object comparison.. 

RestFixture doesn't have any support out of the box for deep JSON object comparison. Instead you can use directly JavaScript. 

From RestFixture 4.1 you can include specific javascript code in the context of the evaluation of the response. Based on [this StackOverflow response](http://stackoverflow.com/questions/1068834/object-comparison-in-javascript) i have created [an example](https://github.com/smartrics/RestFixtureLiveDoc/tree/master/src/main/resources/FitNesseRoot/RestFixtureTests/IssueFixes/Issue176) in the [RestFixtureLiveDoc](https://github.com/smartrics/RestFixtureLiveDoc) repo.

In there I have added a [deepCompare function](https://github.com/smartrics/RestFixtureLiveDoc/blob/master/src/main/resources/FitNesseRoot/files/javascript/deepCompare.js), imported it via the Rest Fixture Config and used in the sample fixture.

    | Table: Rest Fixture Config |  with-deepCompare.js |
    | restfixture.javascript.imports.map | !-  deepCompare=src/main/resources/FitNesseRoot/files/javascript/deepCompare.js-! |
    
    | Table: Rest Fixture |http://${jettyHost}:${jettyPort}| with-deepCompare.js |
    |GET    | /resources/1.json | 200 |Content-Type : application/json | !- /* javascript */
    var expectedJson = {
        'resource' : {
            'name' : 'a funky name',
            'data' : 'an important message'
        }
    };
    deepCompare(jsonbody, expectedJson);
    -!|


More comples JavaScript functions can be created to implement more thorough checks. For example, 
* skip checks on attributes containing timestamps or random numbers 
* use regular expressions to validate attribute values, 
* validate against a JSON schema

These functions operate at a "low level", that is at the "application transport protocol" (the JSON on the wire.) This may be fine for users that have knowledge of how the domain model has been mapped to JSON and are confortable with managing JSON.

-----------

A different approach you can follow - should low level JSON not be suitable for the target audience - is to create an external DSL in the form of high level functions that take the response jsonbody and do the relevant checks. This allows QA people to further abstract from JSON and concentrate their effort on specific domain concepts. 

This DSL can be either done in javascript (using the method above described) or - much better - as [slim script or decision fixtures](http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM) 

The fistures are written in Java - see FitNesse docs - and should take the jsonbody JSON and use to provide the relevant checks. For example

    | GET | /path/to/resource |  |  |  |
    | let | body | js | JSON.stringify(response.jsonbody) | |
    
    | script | checks the response | $body |
    | check | response is a valid order |
    | check | that the order has id | 1234 |
    | check | the amount has been credited | 
    
In essence, your DSL is implemented by the fixtures. 

The focus - in this approach is not on the API but rather in the functionality expressed via the API by the system.

**Comment by EshwarprasadKc** [comment]
can you please tell me right syntax to use it
