### ISSUE TITLE
how to fix 415 Error

### ISSUE THREAD

**Issue by EshwarprasadKc** [smartrics/RestFixture#183]
{
    "status":415,
    "apiMessage":"The server is unable to consume content of type application/vnd.com.covisint.platform.person.v1+json",
    "apiStatusCode":"framework:request:unsupported:mediatype"
}

**Comment by EshwarprasadKc** [comment]
and also tell me how to include dataservice header

**Comment by smartrics** [comment]
I don't understad the question. Please write clearly what the problem is and post an example of the request/response.

**Comment by EshwarprasadKc** [comment]
This is my code 
!define TEST_SYSTEM {slim}
!path C:/RestFixture/target/dependencies/*
!path C:/RestFixture/target/smartrics-RestFixture-4.1-SNAPSHOT.jar
!path C:/RestFixture/slf4j-simple-1.6.6.jar
| Table:smartrics.rest.fitnesse.fixture.RestFixture | http://person-3-0-0-qa.run.covisintrnd.com |
| setHeader | !-Content-Type:application/vnd.com.covisint.platform.person.v1+json
Accept : application/vnd.com.covisint.platform.person.v1+json
x-requestor: [APPCLOUD-QA]APPCLOUD-QA_ADMIN
x-realm : S-PLATFORM-COVS
x-requestor-app : RnD Testing.-! |
| setFileName | ..\RestFixture\FitNesseRoot\FrontPage\Myuserservice\post\Test data\file.json | |
| POST | /persons | 201 | | |
| let | id | header | /persons/(.+) | |
| setFileName | ..\RestFixture\FitNesseRoot\FrontPage\Myuserservice\post\Test data\rightbody.json | |
| PUT |/persons/%id%/accounts/password| 200 | | |
| setBody | {"creator": "[APPCLOUD-QA]APPCLOUD-QA_ADMIN","realm":"SYS","creatorAppId":"2de44e1e-504e-432d-bbe4-cf0c17a8f55e","justification":"I need access.","registrant": {"id":"%id%","realm":"SYS","type":"person"},"servicePackageRequest": {"packageId":"PS-PLATFORM-COVS13976838","realm":"SYS"}} | 
| POST | /requests | 201 | | |
| let | id | header | /requests/(.+) | |
| POST | /requests/tasks/approve?requestId=%id% | 204 | | |

i am getting error called 
{
    "status":415,
    "apiMessage":"The server is unable to consume content of type application/vnd.com.covisint.platform.person.v1+json",
    "apiStatusCode":"framework:request:unsupported:mediatype"
}

**Comment by smartrics** [comment]
That is an application error that Has nothing to do with the RestFixture.

I can see you are setting the content type here

    Content-Type:application/vnd.com.covisint.platform.person.v1+json

And you server is telling you that that's not correct
On 19 Apr 2016 06:22, "EshwarprasadKc" <notifications@github.com> wrote:

This is my code
!define TEST_SYSTEM {slim}
!path C:/RestFixture/target/dependencies/*
!path C:/RestFixture/target/smartrics-RestFixture-4.1-SNAPSHOT.jar
!path C:/RestFixture/slf4j-simple-1.6.6.jar
| Table:smartrics.rest.fitnesse.fixture.RestFixture |
http://person-3-0-0-qa.run.covisintrnd.com |
| setHeader |
!-Content-Type:application/vnd.com.covisint.platform.person.v1+json
Accept : application/vnd.com.covisint.platform.person.v1+json
x-requestor: [APPCLOUD-QA]APPCLOUD-QA_ADMIN
x-realm : S-PLATFORM-COVS
x-requestor-app : RnD Testing.-! |
| setFileName |
..\RestFixture\FitNesseRoot\FrontPage\Myuserservice\post\Test
data\file.json | |
| POST | /persons | 201 | | |
| let | id | header | /persons/(.+) | |
| setFileName |
..\RestFixture\FitNesseRoot\FrontPage\Myuserservice\post\Test
data\rightbody.json | |
| PUT |/persons/%id%/accounts/password| 200 | | |
| setBody | {"creator":
"[APPCLOUD-QA]APPCLOUD-QA_ADMIN","realm":"SYS","creatorAppId":"2de44e1e-504e-432d-bbe4-cf0c17a8f55e","justification":"I
need access.","registrant":
{"id":"%id%","realm":"SYS","type":"person"},"servicePackageRequest":
{"packageId":"PS-PLATFORM-COVS13976838","realm":"SYS"}} |
| POST | /requests | 201 | | |
| let | id | header | /requests/(.+) | |
| POST | /requests/tasks/approve?requestId=%id% | 204 | | |

i am getting error called
{
"status":415,
"apiMessage":"The server is unable to consume content of type
application/vnd.com.covisint.platform.person.v1+json",
"apiStatusCode":"framework:request:unsupported:mediatype"
}

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/smartrics/RestFixture/issues/183#issuecomment-211732425>

**Comment by EshwarprasadKc** [comment]
got it thank you
