### ISSUE TITLE
cannot post when url contains a URL Encoded value %2F (/)

### ISSUE THREAD

**Issue by haroon-sheikh** [smartrics/RestFixture#188]
Hi, I'm looking to post to rabbitmq using their http api i.e.http://hg.rabbitmq.com/rabbitmq-management/raw-file/rabbitmq_v3_3_4/priv/www/api/index.html

And particularly POST to this API `/api/exchanges/vhost/name/publish` where `vhost` is a forward slash.

I can successfully do a POST in Postman with using url encoded forward slash i.e. `/api/exchanges/%2F/name/publish`. However, when I try to do the same using the RestFixture, I'm getting a following 404 response 

```bash
<HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD><BODY><H1>Not Found</H1>The requested document was not found on this server.<P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></BODY></HTML>
```

Would anyone be able to advise please?

**Comment by smartrics** [comment]
Hi have you tried escaping the % with %25 so that your %2F becomes %252F

**Comment by haroon-sheikh** [comment]
Yeah I tried that but didn't work either. returning a 404 again.

**Comment by smartrics** [comment]
You should tell RestFixture that urls are already URL encoded with a specific config. For example

    | Table: Rest Fixture Config | url_esc |
    | restfixture.resource.uris.are.escaped | true |

and then

    | Table: Rest Fixture |http://... | url_esc | 
    |GET    | !-api/exchanges/%2F/name/publish-! |  | |  |

you can also set it into the default config

**Comment by JayashreeNagaraja** [comment]
I have a similar problem.. I want to make a PUT call on a URL which looks like:
/original/596141312_fit_test_text?Policy=%7B%22Version%22%3A%222012-10-17%22%2C%22Statement%22%3A%5B3A%221%22%2C%22Effect%2A%22Allow%22%2CAction%22%3A%5B%22s3%3AObject%ThanEquals%22%3A%7B%22s3%3Acontent-length-range%22%3221073741824%22%5D%7D%7D%7D%5D%7D

 I tried adding: | restfixture.resource.uris.are.escaped | true | to my test in the config section but that does not seem to change the behavior. Also, the URL mentioned above is being picked up from the response of the previous test and I am passing the URL as |PUT|!- %Url% -!| | | |

Rest is continuing to encode the URL with %252 in every occurrence.  PUT call is failing due to this. 

Any help on this??
