### ISSUE TITLE
Feature Request. Add possibility to specify several url's to send a request.

### ISSUE THREAD

**Issue by tbarabanov** [smartrics/RestFixture#192]
It would be great to be abel to specify several url's to send a request.
For instance I would like to send the same GET request to hosts: www.host1.com then www.host2.com so I expect same responses. I do not want to repeat tables in Fitnesse test, just wish to specify url list to send the request.
Also it would be great to be able add comparator for responses. This comparator should check if two endpoints send the same responses.
Thanks.

**Comment by smartrics** [comment]
this feels like more an custom extension only specific to your problem
rather than a generic enhancement of RestFixture.
The word "several" is unclear. Would you run the request in sequence or in
parallel? what if some responses are slow? or if the server responds with
an error?
And for the comparator, what would you compare? the whole response (headers
and body) or only the body?
And for the body, what would make two responses the same? what about if the
responses contain random/time dependant data like timestamps or IDs?

I think your best option is firstly clarify what you really need, then you
can extend RestFixture to code that specific behaviour.

On 16 June 2016 at 13:13, tbarabanov <notifications@github.com> wrote:

> It would be great to be ably to specify several url's to send a request.
> For instance I would like to send the same GET request to hosts:
> www.host1.com then www.host2.com so I expect same responses. I do not
> want to repeat tables in Fitnesse test, just wish to specify url list to
> send the request.
> Also it would be great to be able add comparator for responses. This
> comparator should check if two endpoints send the same responses.
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/smartrics/RestFixture/issues/192>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAImOob3pYOG0-04yaSQYF7ML_6zEiQqks5qMT4FgaJpZM4I3Ujm>
> .
>



-- 
Regards,

 Fabrizio
