### ISSUE TITLE
I find a bug about  let

### ISSUE THREAD

**Issue by cmaster007** [smartrics/RestFixture#243]
let | role1 | js | response.jsonbody.TVVMDC0012.role | AppServer[?]
if AppServer is a wiki word will   conflict

**Comment by smartrics** [comment]
Please try include the expectation in !-  -!

|let | role1 | js | response.jsonbody.TVVMDC0012.role | !-AppServer-! |

On 29 Jan 2018 7:34 a.m., "cmaster007" <notifications@github.com> wrote:

let | role1 | js | response.jsonbody.TVVMDC0012.role | AppServer[?]
if AppServer is a wiki word will conflict

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/smartrics/RestFixture/issues/243>, or mute the thread

**Comment by cmaster007** [comment]
thank you very much
